on:
  push:
    branches:
    - main
  workflow_dispatch:
  

jobs:
  my_job:
    name: create doc
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: brunokrauss/jsdoc-action@3
        with:
          jsdoc-path: 'src'
